const button = document.querySelector("#btn");
const par = document.querySelector("#prediction");
const predictions = [
    "Hoy es un buen día para abrazar fuerte a alguien.",
    "Una sorpresa dulce te espera muy pronto.",
    "Vas a encontrar alegría en los pequeños detalles.",
    "Un café con alguien especial cambiará tu semana.",
    "Un mensaje inesperado te hará sonreír.",
    "Hoy te mereces una siesta larga y sin culpa.",
    "Una estrella fugaz tiene un deseo guardado para ti.",
    "Un día lluvioso te traerá paz y chocolate.",
    "Pronto reirás hasta que te duela la barriga.",
    "Te espera una conversación que calentará tu alma.",
    "Un libro abrirá una puerta nueva en tu mente.",
    "Tus ideas brillan más de lo que crees.",
    "Hoy es el día ideal para bailar solo en casa.",
    "Alguien piensa en ti con mucho cariño.",
    "Una pizza deliciosa está más cerca de lo que crees.",
    "Los abrazos virtuales también cuentan, ¿sabías?",
    "Te llegará una inspiración inesperada esta semana.",
    "Tu risa es medicina para otros.",
    "Tu intuición será tu superpoder hoy.",
    "Se avecina una racha de buena suerte… ¡Prepárate!",
    "Un gato misterioso te está enviando buenos deseos.",
    "Tus pasos te llevarán donde debes estar.",
    "Un té caliente resolverá el 87% de tus problemas.",
    "Un pequeño cambio traerá una gran alegría.",
    "Hoy podrías conocer a alguien muy especial.",
    "Un nuevo comienzo está tocando a tu puerta.",
    "El universo te guiña el ojo… y no es casualidad.",
    "Recibirás amor de la forma más inesperada.",
    "Una playlist te salvará de un mal día.",
    "Se viene un reencuentro que calienta el corazón.",
    "Estás más cerca de tu sueño de lo que imaginas.",
    "Un gesto tuyo alegrará el día de alguien.",
    "Vas a encontrar belleza en algo común.",
    "Tu magia personal está en pleno auge.",
    "Tu paciencia será recompensada con algo sabroso.",
    "Estás por vivir una escena de película romántica.",
    "Un helado te traerá una gran verdad.",
    "El destino tiene una carta cursi para ti.",
    "Eres más adorable que un panda comiendo bambú.",
    "Hoy será un buen día para usar pijama todo el día.",
    "Tus sueños te están aplaudiendo desde el futuro.",
    "Una nueva idea te hará saltar de emoción.",
    "Tu creatividad está por explotar como fuegos artificiales.",
    "Alguien guarda una sorpresa bonita para ti.",
    "Hoy podrías encontrar una moneda de la suerte.",
    "Un gato callejero te hará sentir afortunado.",
    "Una charla de madrugada te dará claridad.",
    "Pronto alguien te dirá: ‘Me haces feliz’.",
    "Un recuerdo feliz tocará tu corazón hoy.",
    "Hay magia en tu manera de mirar.",
    "Una carta bonita está viajando hacia ti.",
    "Eres como una manta suave en invierno.",
    "Hoy podrías llorar... de risa.",
    "Hoy te sentirás abrazado por el universo.",
    "Algo que temías se resolverá con ternura.",
    "Hoy es ideal para ver una comedia romántica.",
    "Tu alegría es contagiosa… ¡sigue esparciéndola!",
    "Una nube con forma extraña te enviará un guiño.",
    "El destino planea un pequeño milagro para ti.",
    "Hoy podrías enamorarte… de un pastel.",
    "Pronto vivirás un momento de película de Pixar.",
    "Tu futuro tiene olor a canela y libros nuevos.",
    "Una taza bonita de té te dará sabiduría.",
    "El universo quiere verte reír más seguido.",
    "Un abrazo que extrañas se acerca silenciosamente.",
    "Estás hecho de polvo de estrellas y chispas dulces.",
    "Pronto descubrirás una coincidencia mágica.",
    "Vas a brillar incluso cuando no lo planeas.",
    "Estás a un paso de algo muy emocionante.",
    "Pronto alguien te mirará como si fueras arte.",
    "Hoy todo saldrá mejor de lo esperado.",
    "Una sonrisa tuya va a cambiar un destino.",
    "Estás rodeado de más amor del que puedes ver.",
    "Pronto vas a reír hasta que se te caigan las lágrimas.",
    "Vas a encontrar belleza en lo más cotidiano.",
    "Alguien muy especial está por cruzar tu camino.",
    "Una carcajada sincera te espera esta semana.",
    "El viento trae buenas vibras hacia ti.",
    "Estás a punto de crear un recuerdo inolvidable.",
    "Todo lo que das con amor vuelve multiplicado.",
    "Eres el respiro de calma en días agitados.",
    "Un gesto pequeño tuyo hará sonreír a alguien hoy.",
    "La dulzura con la que vives es un regalo para el mundo.",
    "Lo que parecía perdido, regresará con más luz.",
    "Tu intuición te llevará por buen camino.",
    "Una tarde tranquila te traerá claridad.",
    "Muy pronto, celebrarás algo bonito.",
    "Eres la inspiración silenciosa de alguien.",
    "Hoy mereces flores, risas y canciones suaves.",
    "Te espera una conversación que calentará tu corazón.",
    "La vida está preparando una coincidencia mágica para ti.",
    "Algo inesperado te hará sentir agradecido/a.",
    "Un sueño que parecía lejano empezará a tomar forma.",
    "El universo te susurra: 'lo estás haciendo bien'.",
    "Hoy es buen día para cuidarte con cariño.",
    "Te espera una señal que te hará sonreír.",
    "La calma llegará cuando más la necesites.",
    "Alguien hablará de ti con mucha admiración.",
    "Te estás convirtiendo en tu mejor versión.",
];

button.addEventListener("click", showPrediction);

function showPrediction() {
    let predictionShowed = predictions[Math.floor(Math.random() * predictions.length)];
    par.style.display = "block";
    par.textContent = predictionShowed;
};